current_version = "0.1.0"

[[files]]
path = "src/rst_package_refs/__init__.py"
search = "__version__ = \"{{current_version}}\""
replace = "__version__ = \"{{new_version}}\""

[[files]]
path = "pyproject.toml"
search = "version = \"{{current_version}}\""
replace = "version = \"{{new_version}}\""

[[files]]
path = "CHANGES.rst"
search = """
v{{ current_version }}
={{#sameLengthChars}}=@{{current_version}}{{/sameLengthChars}}
"""
replace = """
v{{ new_version }}
={{#sameLengthChars}}=@{{new_version}}{{/sameLengthChars}}

:Date: {{ nowFormat.dateISO }} (Asia/Tokyo)

Breaking changes
----------------

Features
--------

Fixes
-----

Others
------

v{{ current_version }}
={{#sameLengthChars}}=@{{current_version}}{{/sameLengthChars}}
"""

[[files]]
path = ".github/release-body.md"
regex = true
search = """
- Changelog is https://github.com/attakei/rst-package-refs/blob/v{{ current_version }}/CHANGES.rst
- You can source diff to (.+)
"""
replace = """
- Changelog is https://github.com/attakei/rst-package-refs/blob/v{{ new_version }}/CHANGES.rst
- You can source diff to https://github.com/attakei/rst-package-refs/compare/v{{ current_version }}..v{{ new_version }}
"""
